# -*- coding: utf-8 -*-
"""lab1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T0Y0aUD2iBXNWPKf2bmOb04x5CNi43l-
"""

#task_1
T=int(input())
if 1<=T<=100:
  for _ in range(T):
    N=int(input())
    if -10**5<=N<=10**5:
      if N%2==0:
        print(f"{N} is an Even number.")
      else:
        print(f"{N} is an Odd number.")

#task_2

T=int(input())
for _ in range(T):
    N=input().split(" ")
    if N[2]=="+":
      print(f"{float(int(N[1])+int(N[3])):.6f}")
    elif N[2]=="-":
      print(f"{float(int(N[1])-int(N[3])):.6f}")
    elif N[2]=="*":
      print(f"{float(int(N[1])*int(N[3])):.6f}")
    elif N[2]=="/":
      print(f"{float(int(N[1])/int(N[3])):.6f}")

#task_3
line1=input().split(" ")
N=int(line1[0])
K=int(line1[1])
line2=input().split(" ")
for i in range(K-1,-1,-1):
   print(int(line2[i]),end=" ")

#task_4
T=int(input())
if 1<=T<=10**4:
 for _ in range(T):
  N=int(input())
  if 1<=N<=10**6:
    print(N*(N+1)//2)

#task_5
def bubblesort(N,arr):
  arr = list(map(int,arr))
  for i in range(N-1):
    flag=False
    for j in range(N-1-i):
      if arr[j]>arr[j+1]:
        arr[j],arr[j+1]=arr[j+1],arr[j]
        flag=True
    if flag==False:
      break
  for i in range(N):
    print(arr[i],end=" ")

N=int(input())
arr=input().split(" ")
bubblesort(N,arr)

#task_6
def mark_sorting(N,id,mark):
   id=list(map(int,id))
   mark=list(map(int,mark))
   count=0
   for i in range(N):
      high_id=i
      for j in range(i+1,N):
         if mark[j]>mark[high_id]:
            high_id=j
         elif mark[j]==mark[high_id]:
            if id[j]<id[high_id]:
             high_id=j
      if high_id!=i:
         mark[i],mark[high_id]=mark[high_id],mark[i]
         id[i],id[high_id]=id[high_id],id[i]
         count+=1
   print(f"Minimum swaps: {count}")
   for i in range(N):
      print(f"ID: {id[i]} Mark: {mark[i]}")





N=int(input())
id=input().split(" ")
mark=input().split(" ")
mark_sorting(N,id,mark)

