# -*- coding: utf-8 -*-
"""lab2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T0Y0aUD2iBXNWPKf2bmOb04x5CNi43l-
"""

#task_1
a=input().split(" ")
s=int(a[0])
max_sum=int(a[1])
b=list(map(int,input().split()))




def func(s,max_sum,b):
  i=0
  j=s-1
  while i<j:
    sum= (b[i]+b[j])
    if sum==max_sum:
        print ( i+1,j+1)
        return
    elif sum < max_sum:
        i+=1
    elif sum > max_sum:
        j-=1
  print(-1)
  return

r=func(s,max_sum,b)

#task_2
a=int(input())
n=list(map(int,input().split()))
b=int(input())
m=list(map(int,input().split()))
l=[]

i=0
j=0
while i<a and j<b:
    if n[i]<= m[j]:
       l.append(n[i])
       i+=1
    else:
       l.append(m[j])
       j += 1

while i < a:
    l.append(n[i])
    i += 1

while j < b:
    l.append(m[j])
    j += 1

print(" ".join(map(str, l)))

#task_3
a=input().split(' ')
len1=int(a[0])
max_sum=int(a[1])
b=list(map(int,input().split(' ')))

def func(len1,maxsum,b):
    i=0
    sum=0
    len2=0
    for j in range(len1):
      sum+=b[j]
      while sum>max_sum and i<=j:
            sum-=b[i]
            i+=1


      len2=max(len2,j-i+1)
    return len2
r=  func(len1,max_sum,b)
print(r)

#task_4
a=int(input().strip())

def func(a):
    for _ in range(a):
      temp=input().strip()
      i=0
      j=len(temp)-1
      r= -1
      while i<=j:
        mid=(i+j)//2
        if temp[mid]=='1' and (mid==0 or temp[mid-1]=='0'):
            r= mid+1
            break
        elif temp[mid]=='1':
            j=mid-1

        elif temp[mid]=='0':
            i=mid+1
      print (r)

b=func(a)

#task_5
a=input().split()
c=int(a[1])
b=list(map(int,input().split()))


def lower(b,v1):
    i=0
    j=len(b)
    while i<j:
        mid=(i+j)//2
        if b[mid]<v1:
            i=mid+1
        else:
            j=mid
    return i

def upper(b,v2):
    i=0
    j=len(b)
    while i<j:
        mid=(i+j)//2
        if b[mid]<=v2:
            i=mid+1
        else:
            j=mid
    return i

for v in range(c):
    v1,v2=map(int,input().split())
    left=lower(b,v1)
    right=upper(b,v2)
    print(right-left)